[theme]
# Merah khas logo Panca Budi untuk tombol dan garis penanda
primaryColor = "#ED1C24" 

# Putih bersih seperti website resminya
backgroundColor = "#FFFFFF" 

# Abu-abu sangat muda untuk membedakan area kotak teks
secondaryBackgroundColor = "#F4F6F9" 

# Teks warna hitam pekat agar profesional
textColor = "#000000" 

font = "sans serif"
